# enable zmk studio for realtime keymap updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# enable zmk mouse functionality
CONFIG_ZMK_POINTING=y

# enable requiring a pin for bluetooth pairing requests
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

# Increase bluetooth transmission power to reduce disconnects between halves
# https://zmk.dev/docs/config/bluetooth
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
